<div style="background-color:#e6f2ff; padding:20px; border-radius:10px;">
<img style="float:left; margin-right:20px;" src='Figures/alinco.png' width="120"/>
<h1 style="color:#000047;">Tarea 1: Modificación de la librería de clase</h1>
<br style="clear:both"/>
</div>

<div style="border-left:4px solid #000047; padding:10px; margin-top:10px; background:#f5f5f5;">
<b>Objetivo:</b> Construir la librería de la clase con el objetivo de organizar código funciones y clases útilies durante el proceso del curso.
</div>

Tomando en cuenta la libreria creada en clase `HyAIA`, y la función de reporte de calidad de datos `dqr()`, realizar lo siguiente:

Modificar la función `dqr()` para tener lo siguiente:

**1.- Modificar la función dqr() para que en el reporte se agregue una columna que sea booleana boolena para representar si una columna es categórica ('Is_categorical') ('Is_categorical' True-->col categorica, False ---> numérica)**

In [2]:
print("El bloque de codigo en la fuicion dqr se implemento en la clase original")
                                                        
#def dqr(self):
    
    #is_categorical = pd.DataFrame(columns=['Is_categorical'])
    #for col in list(self.data.columns.values):
     #   if col in self.categoricos_columns:
      #      is_categorical.loc[col] = [True]
       # else:
        #    is_categorical.loc[col] = [False]        
  
    #return columns_names.join(data_dtypes).join(present_values).join(missing_values).join(unique_values).join(max_values).join(min_values).join(is_categorical)

El bloque de codigo en la fuicion dqr se implemento en la clase original

In [4]:
from HyAIA import HyAIA as hia
import pandas as pd
import numpy as np

df_countries = pd.read_csv('countries.csv', sep=';')
df_countries

,alpha_2,alpha_3,area,capital,continent,currency_code,currency_name,eqivalent_fips_code,fips,geoname_id,languages,name,neighbours,numeric,phone,population,postal_code_format,postal_code_regex,tld
0,AD,AND,468.0,Andorra la Vella,EU,EUR,Euro,NaN,AN,3041565,ca,Andorra,"ES,FR",20,376,84000,AD###,^(?:AD)*(\d{3})$,.ad
1,AE,ARE,82880.0,Abu Dhabi,AS,AED,Dirham,NaN,AE,290557,"ar-AE,fa,en,hi,ur",United Arab Emirates,"SA,OM",784,971,4975593,NaN,NaN,.ae
2,AF,AFG,647500.0,Kabul,AS,AFN,Afghani,NaN,AF,1149361,"fa-AF,ps,uz-AF,tk",Afghanistan,"TM,CN,IR,TJ,PK,UZ",4,93,29121286,NaN,NaN,.af
3,AG,ATG,443.0,St. John's,NaN,XCD,Dollar,NaN,AC,3576396,en-AG,Antigua and Barbuda,NaN,28,+1-268,86754,NaN,NaN,.ag
4,AI,AIA,102.0,The Valley,NaN,XCD,Dollar,NaN,AV,3573511,en-AI,Anguilla,NaN,660,+1-264,13254,NaN,NaN,.ai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,ZA,ZAF,1219912.0,Pretoria,AF,ZAR,Rand,NaN,SF,953987,"zu,xh,af,nso,en-ZA,tn,st,ts,ss,ve,nr",South Africa,"ZW,SZ,MZ,BW,NA,LS",710,27,49000000,####,^(\d{4})$,.za
248,ZM,ZMB,752614.0,Lusaka,AF,ZMW,Kwacha,NaN,ZA,895949,"en-ZM,bem,loz,lun,lue,ny,toi",Zambia,"ZW,TZ,MZ,CD,NA,MW,AO",894,260,13460305,#####,^(\d{5})$,.zm
249,ZW,ZWE,390580.0,Harare,AF,ZWL,Dollar,NaN,ZI,878675,"en-ZW,sn,nr,nd",Zimbabwe,"ZA,MZ,BW,ZM",716,263,13061000,NaN,NaN,.zw
250,CS,SCG,102350.0,Belgrade,EU,RSD,Dinar,NaN,YI,8505033,"cu,hu,sq,sr",Serbia and Montenegro,"AL,HU,MK,RO,HR,BA,BG",891,381,10829175,#####,^(\d{5})$,.cs
251,AN,ANT,960.0,Willemstad,NaN,ANG,Guilder,NaN,NT,8505032,"nl-AN,en,es",Netherlands Antilles,GP,530,599,300000,NaN,NaN,.an

In [11]:

from HyAIA import HyAIA as hia
import pandas as pd
import numpy as np

df_countries = pd.read_csv('countries.csv', sep=';')

hy_countries = hia(df_countries)
hy_countries.dqr()

,Columns_Names,Dtypes,Present_values,Missing_values,Unique_values,Is_categorical,Max_values,Min_values,Mean_values,Std_deviation,Categories
alpha_2,alpha_2,object,251,1,251,True,N/A,N/A,N/A,N/A,"AD, AE, AF, AG, AI ... (+246 más)"
alpha_3,alpha_3,object,252,0,252,True,N/A,N/A,N/A,N/A,"AND, ARE, AFG, ATG, AIA ... (+247 más)"
area,area,float64,252,0,248,False,17100000.0,0.0,595287.86,1904817.77,N/A
capital,capital,object,246,6,244,True,N/A,N/A,N/A,N/A,"Andorra la Vella, Abu Dhabi, Kabul, St. John's..."
continent,continent,object,210,42,6,True,N/A,N/A,N/A,N/A,"EU, AS, AF, AN, SA, OC"
currency_code,currency_code,object,251,1,155,True,N/A,N/A,N/A,N/A,"EUR, AED, AFN, XCD, ALL ... (+150 más)"
currency_name,currency_name,object,251,1,82,True,N/A,N/A,N/A,N/A,"Euro, Dirham, Afghani, Dollar, Lek ... (+77 más)"
eqivalent_fips_code,eqivalent_fips_code,object,1,251,1,False,N/A,N/A,N/A,N/A,N/A
fips,fips,object,249,3,249,True,N/A,N/A,N/A,N/A,"AN, AE, AF, AC, AV ... (+244 más)"
geoname_id,geoname_id,int64,252,0,252,False,8505033,49518,2427869.98,1632092.92,N/A
languages,languages,object,249,3,246,True,N/A,N/A,N/A,N/A,"ca, ar-AE,fa,en,hi,ur, fa-AF,ps,uz-AF,tk, en-A..."
name,name,object,252,0,252,True,N/A,N/A,N/A,N/A,"Andorra, United Arab Emirates, Afghanistan, An..."
neighbours,neighbours,object,165,87,159,True,N/A,N/A,N/A,N/A,"ES,FR, SA,OM, TM,CN,IR,TJ,PK,UZ, MK,GR,ME,RS,X..."
numeric,numeric,int64,252,0,252,False,894,0,434.31,254.66,N/A
phone,phone,object,247,5,233,True,N/A,N/A,N/A,N/A,"376, 971, 93, +1-268, +1-264 ... (+228 más)"
population,population,int64,252,0,249,False,1330044000,0,27276790.08,116412698.52,N/A
postal_code_format,postal_code_format,object,154,98,45,True,N/A,N/A,N/A,N/A,"AD###, ######, @####@@@, ####, ##### ... (+40 ..."
postal_code_regex,postal_code_regex,object,152,100,54,True,N/A,N/A,N/A,N/A,"^(?:AD)*(\d{3})$, ^(\d{6})$, ^[A-Z]?\d{4}[A-Z]..."
tld,tld,object,250,2,248,True,N/A,N/A,N/A,N/A,".ad, .ae, .af, .ag, .ai ... (+243 más)"

In [12]:


from HyAIA import HyAIA as hia
import pandas as pd
import numpy as np

df_countries = pd.read_csv('countries.csv', sep=';')

hy_countries = hia(df_countries)
hy_countries.dqr()['Is_categorical']

alpha_2                 True
alpha_3                 True
area                   False
capital                 True
continent               True
currency_code           True
currency_name           True
eqivalent_fips_code    False
fips                    True
geoname_id             False
languages               True
name                    True
neighbours              True
numeric                False
phone                   True
population             False
postal_code_format      True
postal_code_regex       True
tld                     True
Name: Is_categorical, dtype: bool

**2.- Modificar la función dqr() para que en el reporte se agregue una columna con las categorías de las columnas (valores unicos) que resulten ser categóricas (si las categorias > 10, no agregar esas categorias)**

In [7]:
print("Bloque de codigo implementado en la clase HyAIA")
#categories_values = pd.DataFrame(columns=['Categories'])
 #       for col in list(self.data.columns.values):
  #          if col in self.categoricos_columns:
   #             unique_cats = self.data[col].dropna().unique()
    #            if len(unique_cats) <= 10:
     #               # se muestran las categorias si son menos de 10
      #              categories_list = ', '.join(
       #                 [str(cat) for cat in unique_cats])
        #            categories_values.loc[col] = [categories_list]
         #       else:
                    # Si  son mas de 10 se muestran 5 y puntos
          #          first_5 = ', '.join([str(cat) for cat in unique_cats[:5]])
           #         categories_values.loc[col] = [
            #            f"{first_5} ... (+{len(unique_cats)-5} más)"]
            #else:
                # no categoricas N/A
            #    categories_values.loc[col] = ['N/A']

Bloque de codigo implementado en la clase HyAIA

In [2]:
from HyAIA import HyAIA as hia2
import pandas as pd
import numpy as np

df_countries = pd.read_csv('countries.csv', sep=';')

hy_countries = hia2(df_countries)
hy_countries.dqr()

,Columns_Names,Dtypes,Present_values,Missing_values,Unique_values,Is_categorical,Max_values,Min_values,Mean_values,Std_deviation,Categories
alpha_2,alpha_2,object,251,1,251,True,N/A,N/A,N/A,N/A,"AD, AE, AF, AG, AI ... (+246 más)"
alpha_3,alpha_3,object,252,0,252,True,N/A,N/A,N/A,N/A,"AND, ARE, AFG, ATG, AIA ... (+247 más)"
area,area,float64,252,0,248,False,17100000.0,0.0,595287.86,1904817.77,N/A
capital,capital,object,246,6,244,True,N/A,N/A,N/A,N/A,"Andorra la Vella, Abu Dhabi, Kabul, St. John's..."
continent,continent,object,210,42,6,True,N/A,N/A,N/A,N/A,"EU, AS, AF, AN, SA, OC"
currency_code,currency_code,object,251,1,155,True,N/A,N/A,N/A,N/A,"EUR, AED, AFN, XCD, ALL ... (+150 más)"
currency_name,currency_name,object,251,1,82,True,N/A,N/A,N/A,N/A,"Euro, Dirham, Afghani, Dollar, Lek ... (+77 más)"
eqivalent_fips_code,eqivalent_fips_code,object,1,251,1,False,N/A,N/A,N/A,N/A,N/A
fips,fips,object,249,3,249,True,N/A,N/A,N/A,N/A,"AN, AE, AF, AC, AV ... (+244 más)"
geoname_id,geoname_id,int64,252,0,252,False,8505033,49518,2427869.98,1632092.92,N/A
languages,languages,object,249,3,246,True,N/A,N/A,N/A,N/A,"ca, ar-AE,fa,en,hi,ur, fa-AF,ps,uz-AF,tk, en-A..."
name,name,object,252,0,252,True,N/A,N/A,N/A,N/A,"Andorra, United Arab Emirates, Afghanistan, An..."
neighbours,neighbours,object,165,87,159,True,N/A,N/A,N/A,N/A,"ES,FR, SA,OM, TM,CN,IR,TJ,PK,UZ, MK,GR,ME,RS,X..."
numeric,numeric,int64,252,0,252,False,894,0,434.31,254.66,N/A
phone,phone,object,247,5,233,True,N/A,N/A,N/A,N/A,"376, 971, 93, +1-268, +1-264 ... (+228 más)"
population,population,int64,252,0,249,False,1330044000,0,27276790.08,116412698.52,N/A
postal_code_format,postal_code_format,object,154,98,45,True,N/A,N/A,N/A,N/A,"AD###, ######, @####@@@, ####, ##### ... (+40 ..."
postal_code_regex,postal_code_regex,object,152,100,54,True,N/A,N/A,N/A,N/A,"^(?:AD)*(\d{3})$, ^(\d{6})$, ^[A-Z]?\d{4}[A-Z]..."
tld,tld,object,250,2,248,True,N/A,N/A,N/A,N/A,".ad, .ae, .af, .ag, .ai ... (+243 más)"

In [13]:
from HyAIA import HyAIA as hia
import pandas as pd
import numpy as np

df_countries = pd.read_csv('countries.csv', sep=';')

hy_countries = hia(df_countries)
hy_countries.dqr()['Categories']

alpha_2                                AD, AE, AF, AG, AI ... (+246 más)
alpha_3                           AND, ARE, AFG, ATG, AIA ... (+247 más)
area                                                                 N/A
capital                Andorra la Vella, Abu Dhabi, Kabul, St. John's...
continent                                         EU, AS, AF, AN, SA, OC
currency_code                     EUR, AED, AFN, XCD, ALL ... (+150 más)
currency_name           Euro, Dirham, Afghani, Dollar, Lek ... (+77 más)
eqivalent_fips_code                                                  N/A
fips                                   AN, AE, AF, AC, AV ... (+244 más)
geoname_id                                                           N/A
languages              ca, ar-AE,fa,en,hi,ur, fa-AF,ps,uz-AF,tk, en-A...
name                   Andorra, United Arab Emirates, Afghanistan, An...
neighbours             ES,FR, SA,OM, TM,CN,IR,TJ,PK,UZ, MK,GR,ME,RS,X...
numeric                                                              N/A
phone                        376, 971, 93, +1-268, +1-264 ... (+228 más)
population                                                           N/A
postal_code_format     AD###, ######, @####@@@, ####, ##### ... (+40 ...
postal_code_regex      ^(?:AD)*(\d{3})$, ^(\d{6})$, ^[A-Z]?\d{4}[A-Z]...
tld                               .ad, .ae, .af, .ag, .ai ... (+243 más)
Name: Categories, dtype: object

**3.- Aplicar el análisis estadístico de las columnas creadas (max, min, mean, std) solo para las columnas que sean numéricas ('Is_categorical' == False)**

In [ ]:
    # Lista de valores máximos
    # max_values = pd.DataFrame(columns=['Max_values'])
    # for col in list(self.data.columns.values):
    #     if not is_categorical.loc[col, 'Is_categorical']:  # Solo para numéricas
    #         try:
    #             max_values.loc[col] = [self.data[col].max()]
    #         except:
    #             max_values.loc[col] = ['N/A']
    #     else:
    #         max_values.loc[col] = ['N/A']  # Para categóricas

    # Lista de valores mínimos
    # min_values = pd.DataFrame(columns=['Min_values'])
    # for col in list(self.data.columns.values):
    #     if not is_categorical.loc[col, 'Is_categorical']:  # Solo para numéricas
    #         try:
    #             min_values.loc[col] = [self.data[col].min()]
    #         except:
    #             min_values.loc[col] = ['N/A']
    #     else:
    #         min_values.loc[col] = ['N/A']  # Para categóricas

    # Lista de valores con su desviación estándar
    # std_values = pd.DataFrame(columns=['Std_deviation'])
    # for col in list(self.data.columns.values):
    #     if not is_categorical.loc[col, 'Is_categorical']:  # Solo para numéricas
    #         try:
    #             std_val = self.data[col].std()
    #             std_values.loc[col] = [round(std_val, 2)]
    #         except:
    #             std_values.loc[col] = ['N/A']
    #     else:
    #         std_values.loc[col] = ['N/A']  # Para categóricas

    # Lista de valores con la media 
    # mean_values = pd.DataFrame(columns=['Mean_values'])
    # for col in list(self.data.columns.values):
    #     if not is_categorical.loc[col, 'Is_categorical']:  # Solo para numéricas
    #         try:
    #             mean_val = self.data[col].mean()
    #             mean_values.loc[col] = [round(mean_val, 2)]
    #         except:
    #             mean_values.loc[col] = ['N/A']
    #     else:
    #         mean_values.loc[col] = ['N/A']  # Para categóricas

In [1]:
from HyAIA import HyAIA as hia2
import pandas as pd
import numpy as np

df_countries = pd.read_csv('countries.csv', sep=';')

hy_countries = hia2(df_countries)
hy_countries.dqr()

,Columns_Names,Dtypes,Present_values,Missing_values,Unique_values,Is_categorical,Max_values,Min_values,Mean_values,Std_deviation,Categories
alpha_2,alpha_2,object,251,1,251,True,N/A,N/A,N/A,N/A,"AD, AE, AF, AG, AI ... (+246 más)"
alpha_3,alpha_3,object,252,0,252,True,N/A,N/A,N/A,N/A,"AND, ARE, AFG, ATG, AIA ... (+247 más)"
area,area,float64,252,0,248,False,17100000.0,0.0,595287.86,1904817.77,N/A
capital,capital,object,246,6,244,True,N/A,N/A,N/A,N/A,"Andorra la Vella, Abu Dhabi, Kabul, St. John's..."
continent,continent,object,210,42,6,True,N/A,N/A,N/A,N/A,"EU, AS, AF, AN, SA, OC"
currency_code,currency_code,object,251,1,155,True,N/A,N/A,N/A,N/A,"EUR, AED, AFN, XCD, ALL ... (+150 más)"
currency_name,currency_name,object,251,1,82,True,N/A,N/A,N/A,N/A,"Euro, Dirham, Afghani, Dollar, Lek ... (+77 más)"
eqivalent_fips_code,eqivalent_fips_code,object,1,251,1,False,N/A,N/A,N/A,N/A,N/A
fips,fips,object,249,3,249,True,N/A,N/A,N/A,N/A,"AN, AE, AF, AC, AV ... (+244 más)"
geoname_id,geoname_id,int64,252,0,252,False,8505033,49518,2427869.98,1632092.92,N/A
languages,languages,object,249,3,246,True,N/A,N/A,N/A,N/A,"ca, ar-AE,fa,en,hi,ur, fa-AF,ps,uz-AF,tk, en-A..."
name,name,object,252,0,252,True,N/A,N/A,N/A,N/A,"Andorra, United Arab Emirates, Afghanistan, An..."
neighbours,neighbours,object,165,87,159,True,N/A,N/A,N/A,N/A,"ES,FR, SA,OM, TM,CN,IR,TJ,PK,UZ, MK,GR,ME,RS,X..."
numeric,numeric,int64,252,0,252,False,894,0,434.31,254.66,N/A
phone,phone,object,247,5,233,True,N/A,N/A,N/A,N/A,"376, 971, 93, +1-268, +1-264 ... (+228 más)"
population,population,int64,252,0,249,False,1330044000,0,27276790.08,116412698.52,N/A
postal_code_format,postal_code_format,object,154,98,45,True,N/A,N/A,N/A,N/A,"AD###, ######, @####@@@, ####, ##### ... (+40 ..."
postal_code_regex,postal_code_regex,object,152,100,54,True,N/A,N/A,N/A,N/A,"^(?:AD)*(\d{3})$, ^(\d{6})$, ^[A-Z]?\d{4}[A-Z]..."
tld,tld,object,250,2,248,True,N/A,N/A,N/A,N/A,".ad, .ae, .af, .ag, .ai ... (+243 más)"

In [16]:
from HyAIA import HyAIA as hia
import pandas as pd
import numpy as np

df_countries = pd.read_csv('countries.csv', sep=';')

hy_countries = hia(df_countries)
hy_countries.dqr()[['Max_values','Min_values','Mean_values','Std_deviation']]

                     Max_values Min_values  Mean_values Std_deviation
alpha_2                     N/A        N/A          N/A           N/A
alpha_3                     N/A        N/A          N/A           N/A
area                 17100000.0        0.0    595287.86    1904817.77
capital                     N/A        N/A          N/A           N/A
continent                   N/A        N/A          N/A           N/A
currency_code               N/A        N/A          N/A           N/A
currency_name               N/A        N/A          N/A           N/A
eqivalent_fips_code         N/A        N/A          N/A           N/A
fips                        N/A        N/A          N/A           N/A
geoname_id              8505033      49518   2427869.98    1632092.92
languages                   N/A        N/A          N/A           N/A
name                        N/A        N/A          N/A           N/A
neighbours                  N/A        N/A          N/A           N/A
numeric                     894          0       434.31        254.66
phone                       N/A        N/A          N/A           N/A
population           1330044000          0  27276790.08  116412698.52
postal_code_format          N/A        N/A          N/A           N/A
postal_code_regex           N/A        N/A          N/A           N/A
tld                         N/A        N/A          N/A           N/A