<div style="background-color:#000047; padding: 30px; border-radius: 10px; color: white; text-align: center;">
    <img src='Figures/alinco.png' style="height: 100px; margin-bottom: 10px;"/>
    <h1>Extracción de Datos de Diferentes Fuentes</h1>
</div>

La **extracción de datos** es el proceso de obtener información relevante desde diversas fuentes y formatos, como archivos de texto, hojas de cálculo, bases de datos, imágenes, archivos web, APIs, entre otros. En la actualidad, los datos se encuentran dispersos y almacenados en múltiples formas, por lo que saber cómo acceder, limpiar y transformar estos datos es una habilidad fundamental.

#### ¿Por qué es importante la extracción de datos?

- Permite **integrar información** de diferentes sistemas y plataformas.
- Es el primer paso para el **análisis de datos** y la toma de decisiones basada en evidencia.
- Facilita la **automatización** de procesos y la actualización constante de información.
- Es esencial para la **preparación de datos** en proyectos de ciencia de datos e inteligencia artificial.

En proyectos de **Inteligencia Artificial (IA)**, la calidad y diversidad de los datos es clave para entrenar modelos robustos y precisos. La extracción de datos permite:

- **Construir datasets** a partir de fuentes reales y actualizadas.
- **Preprocesar y limpiar** la información antes de alimentar algoritmos de machine learning.
- **Enriquecer modelos** combinando datos estructurados (tablas, bases de datos) y no estructurados (texto, imágenes, audio).
- **Automatizar la recolección** de datos para sistemas de IA en producción.

Dominar las técnicas de extracción de datos te permitirá abordar problemas complejos, crear soluciones inteligentes y aprovechar el potencial de la IA en cualquier área profesional.

<div style="background-color:#e6f2ff; border-left:4px solid #000047; padding:10px;">
En este notebook aprenderás a extraer datos desde archivos CSV, Excel, texto, JSON, XML, imágenes, HTML y SHP, utilizando Python y sus principales librerías.
</div>

## Cargar archivos

In [15]:
# Almacenamos la ruta de los archivos en una variable
ruta='Data/'

# Archivos Excel y CSV

Los archivos Excel (`.xlsx`, `.xls`) y CSV (`.csv`) son formatos tabulares ampliamente utilizados para almacenar datos estructurados. Python, a través de la librería `pandas`, permite leer y manipular estos archivos de manera sencilla y eficiente.

In [16]:
import pandas as pd

In [17]:
df_csv = pd.read_csv(ruta+'df_tabla2.csv')
print('Contenido del archivo CSV:')
print(df_csv)

Contenido del archivo CSV:
   Unnamed: 0        country  rank  year   gdppc
0           0  Liechtenstein     1  2008  141100
1           1      Singapore     4  2011   59900
2           2         Panama    68  2011   13600

# Archivos de texto
### De texto a `DataFrame`

`pd.read_fwf` de pandas se utiliza para leer archivos de texto con columnas de ancho fijo (fixed-width formatted lines) y cargarlos en un DataFrame

In [18]:
# Extracción a partir de texto separado por tabular
pd.read_fwf(ruta+'texto_2.txt',header=None) # No se puede especificar el separador

         0    1   2
0      Ana  1.0  10
1     Beto  1.1  10
2  Alfredo  6.0   9
3  Armando  5.0   9

`read_table` de pandas se utiliza para leer archivos de texto delimitados (por defecto, separados por tabulaciones) y cargarlos en un DataFrame

In [19]:
pd.read_table(ruta+'texto_2.txt',header=None) # sep='\t'

          0    1   2
0  Ana       1.0  10
1  Beto      1.1  10
2  Alfredo   6.0   9
3  Armando   5.0   9

In [20]:
# Extracción a partir de texto separado por comas
pd.read_table(ruta+'texto_1.txt',sep=',',header=None)

         0    1   2
0      Ana  1.0  10
1     Beto  1.1  10
2  Alfredo  6.0   9
3  Armando  5.0   9

In [21]:
pd.read_table(ruta+'texto_1.txt',sep=' ',header=None)

          0     1   2
0      Ana,    1,  10
1     Beto,  1.1,  10
2  Alfredo,    6,   9
3  Armando,    5,   9

In [22]:
pd.read_csv(ruta+'texto_2.txt',header=None,sep='\t') # sep=','

          0    1   2
0  Ana       1.0  10
1  Beto      1.1  10
2  Alfredo   6.0   9
3  Armando   5.0   9

In [23]:
# Conversión de archivo a variable
file=open(ruta+'texto_3.txt')     # Abrir...
texto=file.read()
file.close()                      # ...despues cerrar

In [24]:
texto

'En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivÃ\xada un hidalgo de los de lanza en astillero, adarga antigua, rocÃ³n flaco y galgo corredor. Una olla de algo mÃ¡s vaca que carnero, salpicÃ³n las mÃ¡s noches, duelos y quebrantos los sÃ¡bados, lantejas los viernes, algÃºn palomino de aÃ±adidura los domingos, consumÃ\xadan las tres partes de su hacienda. El resto della concluÃ\xadan sayo de velarte, calzas de velludo para las fiestas, con sus pantuflos de lo mesmo, y los dÃ\xadas de entresemana se honraba con su vellorÃ\xad de lo mÃ¡s fino. TenÃ\xada en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que asÃ\xad ensillaba el rocÃ\xadn como tomaba la podadera. Frisaba la edad de nuestro hidalgo con los cincuenta aÃ±os; era de complexiÃ³n recia, seco de carnes, enjuto de rostro, gran madrugador y amigo de la caza. Quieren decir que tenÃ\xada el sobrenombre de Quijada, o Quesada, que en esto hay alguna diferencia en los autores que deste caso escriben; aunque por conjeturas verosÃ\xadmiles se deja entender que se llamaba Quijana. Pero esto importa poco a nuestro cuento: basta que en la narraciÃ³n dÃ©l no se salga un punto de la verdad.'

In [25]:
# Si ocurre un error durante la ejecución, la variable file se cierra siempre:
with open(ruta+'texto_3.txt') as file:
  texto=file.read()

In [26]:
texto

'En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivÃ\xada un hidalgo de los de lanza en astillero, adarga antigua, rocÃ³n flaco y galgo corredor. Una olla de algo mÃ¡s vaca que carnero, salpicÃ³n las mÃ¡s noches, duelos y quebrantos los sÃ¡bados, lantejas los viernes, algÃºn palomino de aÃ±adidura los domingos, consumÃ\xadan las tres partes de su hacienda. El resto della concluÃ\xadan sayo de velarte, calzas de velludo para las fiestas, con sus pantuflos de lo mesmo, y los dÃ\xadas de entresemana se honraba con su vellorÃ\xad de lo mÃ¡s fino. TenÃ\xada en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que asÃ\xad ensillaba el rocÃ\xadn como tomaba la podadera. Frisaba la edad de nuestro hidalgo con los cincuenta aÃ±os; era de complexiÃ³n recia, seco de carnes, enjuto de rostro, gran madrugador y amigo de la caza. Quieren decir que tenÃ\xada el sobrenombre de Quijada, o Quesada, que en esto hay alguna diferencia en los autores que deste caso escriben; aunque por conjeturas verosÃ\xadmiles se deja entender que se llamaba Quijana. Pero esto importa poco a nuestro cuento: basta que en la narraciÃ³n dÃ©l no se salga un punto de la verdad.'

In [27]:
# Separamos cada palabra de la variable de texto
texto.split()

['En',
 'un',
 'lugar',
 'de',
 'la',
 'Mancha,',
 'de',
 'cuyo',
 'nombre',
 'no',
 'quiero',
 'acordarme,',
 'no',
 'ha',
 'mucho',
 'tiempo',
 'que',
 'vivÃ\xada',
 'un',
 'hidalgo',
 'de',
 'los',
 'de',
 'lanza',
 'en',
 'astillero,',
 'adarga',
 'antigua,',
 'rocÃ³n',
 'flaco',
 'y',
 'galgo',
 'corredor.',
 'Una',
 'olla',
 'de',
 'algo',
 'mÃ¡s',
 'vaca',
 'que',
 'carnero,',
 'salpicÃ³n',
 'las',
 'mÃ¡s',
 'noches,',
 'duelos',
 'y',
 'quebrantos',
 'los',
 'sÃ¡bados,',
 'lantejas',
 'los',
 'viernes,',
 'algÃºn',
 'palomino',
 'de',
 'aÃ±adidura',
 'los',
 'domingos,',
 'consumÃ\xadan',
 'las',
 'tres',
 'partes',
 'de',
 'su',
 'hacienda.',
 'El',
 'resto',
 'della',
 'concluÃ\xadan',
 'sayo',
 'de',
 'velarte,',
 'calzas',
 'de',
 'velludo',
 'para',
 'las',
 'fiestas,',
 'con',
 'sus',
 'pantuflos',
 'de',
 'lo',
 'mesmo,',
 'y',
 'los',
 'dÃ\xadas',
 'de',
 'entresemana',
 'se',
 'honraba',
 'con',
 'su',
 'vellorÃ\xad',
 'de',
 'lo',
 'mÃ¡s',
 'fino.',
 'TenÃ\xada',
 'en',
 'su',
 'casa',
 'una',
 'ama',
 'que',
 'pasaba',
 'de',
 'los',
 'cuarenta,',
 'y',
 'una',
 'sobrina',
 'que',
 'no',
 'llegaba',
 'a',
 'los',
 'veinte,',
 'y',
 'un',
 'mozo',
 'de',
 'campo',
 'y',
 'plaza,',
 'que',
 'asÃ\xad',
 'ensillaba',
 'el',
 'rocÃ\xadn',
 'como',
 'tomaba',
 'la',
 'podadera.',
 'Frisaba',
 'la',
 'edad',
 'de',
 'nuestro',
 'hidalgo',
 'con',
 'los',
 'cincuenta',
 'aÃ±os;',
 'era',
 'de',
 'complexiÃ³n',
 'recia,',
 'seco',
 'de',
 'carnes,',
 'enjuto',
 'de',
 'rostro,',
 'gran',
 'madrugador',
 'y',
 'amigo',
 'de',
 'la',
 'caza.',
 'Quieren',
 'decir',
 'que',
 'tenÃ\xada',
 'el',
 'sobrenombre',
 'de',
 'Quijada,',
 'o',
 'Quesada,',
 'que',
 'en',
 'esto',
 'hay',
 'alguna',
 'diferencia',
 'en',
 'los',
 'autores',
 'que',
 'deste',
 'caso',
 'escriben;',
 'aunque',
 'por',
 'conjeturas',
 'verosÃ\xadmiles',
 'se',
 'deja',
 'entender',
 'que',
 'se',
 'llamaba',
 'Quijana.',
 'Pero',
 'esto',
 'importa',
 'poco',
 'a',
 'nuestro',
 'cuento:',
 'basta',
 'que',
 'en',
 'la',
 'narraciÃ³n',
 'dÃ©l',
 'no',
 'se',
 'salga',
 'un',
 'punto',
 'de',
 'la',
 'verdad.']

In [28]:
texto.split?

Signature: texto.split(sep=None, maxsplit=-1)
Docstring:
Return a list of the substrings in the string, using sep as the separator string.

  sep
    The separator used to split the string.

    When set to None (the default value), will split on any whitespace
    character (including \n \r \t \f and spaces) and will discard
    empty strings from the result.
  maxsplit
    Maximum number of splits.
    -1 (the default value) means no limit.

Splitting starts at the front of the string and works to the end.

Note, str.split() is mainly useful for data that has been intentionally
delimited.  With natural text that includes punctuation, consider using
the regular expression module.
Type:      builtin_function_or_method

### Expresiones regulares

Las <b>expresiones regulares</b> son patrones que permiten buscar, extraer, validar y manipular texto de manera flexible y eficiente. Son esenciales para limpiar datos, extraer información y validar formatos en archivos de texto.

### Caracteres y operadores básicos

| Símbolo | Significado | Ejemplo |
|---------|-------------|---------|
| `.`     | Cualquier carácter | `a.b` encuentra 'acb', 'aab', etc. |
| `\d`   | Dígito (0-9) | `\d\d` encuentra dos dígitos |
| `\w`   | Carácter alfanumérico | `\w+` encuentra palabras |
| `\s`   | Espacio en blanco | `\s+` encuentra espacios |
| `*`     | Cero o más repeticiones | `ab*` encuentra 'a', 'ab', 'abb', ... |
| `+`     | Una o más repeticiones | `ab+` encuentra 'ab', 'abb', ... |
| `?`     | Cero o una repetición | `ab?` encuentra 'a', 'ab' |
| `^`     | Inicio de línea | `^Hola` encuentra líneas que empiezan con 'Hola' |
| `$`     | Fin de línea | `mundo$` encuentra líneas que terminan con 'mundo' |
| `[abc]` | Cualquier carácter a, b o c | `[aeiou]` encuentra vocales |
| `( )`   | Agrupación | `(abc)+` encuentra 'abc', 'abcabc', ... |

### Funciones principales en Python (`re`)

- `re.search(patron, texto)`: Busca el patrón en el texto y devuelve el primer resultado.
- `re.match(patron, texto)`: Verifica si el patrón coincide al inicio del texto.
- `re.findall(patron, texto)`: Devuelve todas las coincidencias del patrón.
- `re.sub(patron, reemplazo, texto)`: Reemplaza coincidencias por otro texto.

### Ejemplo: Buscar correos electrónicos

In [29]:
import re

texto_correo = "Mi correo es gdesirena@outlook.mx pero anteriormente usaba gdesirena@gmail.com"
patron = r"\w+@\w+\.\w+"

### Ejemplo: Extraer dominios de correos

In [30]:
dominios = re.findall(r'@([\w\.-]+)', texto_correo)
print('Dominios encontrados:', dominios)

Dominios encontrados: ['outlook.mx', 'gmail.com']

### Ejemplo: Buscar fechas en formato DD/MM/AAAA

In [31]:
texto_fechas = 'algunas fechas importantes son 15/09/2023 y 01/01/2024.' 
fechas = re.findall(r'\b\d{2}/\d{2}/\d{4}\b', texto_fechas)
print('Fechas encontradas:', fechas)

Fechas encontradas: ['15/09/2023', '01/01/2024']

### Ejemplo: Validar números de teléfono

Busca números en formato internacional (+52 33 1234 5678):

In [32]:
texto_tel = 'Mi número es +52 33 1234 5678 y el de mi amigo es +52 55 8765 4321.'
patron_tel = r'\+\d{2}\s\d{2}\s\d{4}\s\d{4}'
telefonos = re.findall(patron_tel, texto_tel)
print('Teléfonos encontrados:', telefonos)

Teléfonos encontrados: ['+52 33 1234 5678', '+52 55 8765 4321']

### Ejemplo: Reemplazo de texto

Reemplaza todos los dígitos por 'X':

In [33]:
texto = 'Mi clave es 1234 y mi usuario es user01.'
nuevo_texto = re.sub(r'\d', 'X', texto)
print(nuevo_texto)

Mi clave es XXXX y mi usuario es userXX.

### Ejemplo: Conteo de palabras usando regex

In [34]:
L = re.split(r'\W', texto)
S = set(L)
S.discard('')
d = {}
for palabra in S:
    d[palabra] = len(re.findall(palabra, texto, flags=re.I))
d

{'clave': 1,
 'Mi': 2,
 '1234': 1,
 'es': 2,
 'usuario': 1,
 'mi': 2,
 'user01': 1,
 'y': 1}

### Ejercicio 1

Busca todas las palabras que empiezan con la letra 'u' en el texto anterior.

In [35]:
with open(ruta+'texto_3.txt') as file:
  texto=file.read()
texto

'En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivÃ\xada un hidalgo de los de lanza en astillero, adarga antigua, rocÃ³n flaco y galgo corredor. Una olla de algo mÃ¡s vaca que carnero, salpicÃ³n las mÃ¡s noches, duelos y quebrantos los sÃ¡bados, lantejas los viernes, algÃºn palomino de aÃ±adidura los domingos, consumÃ\xadan las tres partes de su hacienda. El resto della concluÃ\xadan sayo de velarte, calzas de velludo para las fiestas, con sus pantuflos de lo mesmo, y los dÃ\xadas de entresemana se honraba con su vellorÃ\xad de lo mÃ¡s fino. TenÃ\xada en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que asÃ\xad ensillaba el rocÃ\xadn como tomaba la podadera. Frisaba la edad de nuestro hidalgo con los cincuenta aÃ±os; era de complexiÃ³n recia, seco de carnes, enjuto de rostro, gran madrugador y amigo de la caza. Quieren decir que tenÃ\xada el sobrenombre de Quijada, o Quesada, que en esto hay alguna diferencia en los autores que deste caso escriben; aunque por conjeturas verosÃ\xadmiles se deja entender que se llamaba Quijana. Pero esto importa poco a nuestro cuento: basta que en la narraciÃ³n dÃ©l no se salga un punto de la verdad.'

In [36]:
# Tu código aquí
patron = r'\bu\w*'
re.findall(patron,texto)

['un', 'un', 'una', 'una', 'un', 'un']

### Ejercicio 2

Extrae todos los números de una cadena de texto y conviértelos a enteros.

In [37]:
# Tu código aquí
texo2="ssf 44 d 4 ff ef 55 6 ee 5.5"
patron = r'\d+\.?\d*'

listRes =re.findall(patron,texo2)

for item in listRes:
    print(int(float(item)))

44
4
55
6
5

### Recursos útiles

- [regex101.com](https://regex101.com/) - expresiones regulares en línea.
- [Documentación oficial de re](https://docs.python.org/3/library/re.html)

<div style="background-color:#e6f2ff; border-left:4px solid #000047; padding:10px;">
Las expresiones regulares son una herramienta poderosa para la limpieza y extracción de datos en proyectos de IA y ciencia de datos.
</div>

# Archivos excel

In [38]:
import pandas as pd
# A partir de la función
ruta='Data/'
pd.read_excel(ruta+'API_SI.POV.DDAY_DS2_en_excel_v2_1930012.xls')

ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 2.0.1 for xls Excel support Use pip or conda to install xlrd.

In [ ]:
# Importamos la clase ExcelFile
from pandas import ExcelFile

In [ ]:
# A partir de la clase
obj=ExcelFile(ruta+'API_SI.POV.DDAY_DS2_en_excel_v2_1930012.xls')
obj.parse() # Importa la primera página

ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 2.0.1 for xls Excel support Use pip or conda to install xlrd.

# Archivos JSON

El formato JSON (JavaScript Object Notation) es ampliamente utilizado para el intercambio de datos, especialmente en aplicaciones web y APIs. Python incluye la librería estándar `json` para leer y manipular archivos JSON.

In [ ]:
import json

json_data = '{"personas": [{"nombre": "Ana", "edad": 23}, {"nombre": "Luis", "edad": 31}]}'

In [ ]:
from pandas import json_normalize

In [ ]:
df_json['categories'][0]

NameError: name 'df_json' is not defined

# Archivos XML

El formato XML es común para el intercambio de datos estructurados. Python ofrece la librería estándar `xml.etree.ElementTree` para analizar y extraer información de archivos XML.

In [ ]:
import xml.etree.ElementTree as ET
import pandas as pd

In [ ]:
xml_data = '''
<personas>
  <persona>
    <nombre>Ana</nombre>
    <edad>23</edad>
  </persona>
  <persona>
    <nombre>Luis</nombre>
    <edad>31</edad>
  </persona>
</personas>
'''

In [ ]:

root = ET.fromstring(xml_data)
print('Personas extraídas del archivo XML:')
for persona in root.findall('persona'):
    nombre = persona.find('nombre').text
    edad = persona.find('edad').text
    print(f'Nombre: {nombre}, Edad: {edad}')

Personas extraídas del archivo XML:
Nombre: Ana, Edad: 23
Nombre: Luis, Edad: 31

###### Ejemplo con tabla_1.xml

In [ ]:
ruta="Data/"
archivo_1=ET.parse(ruta+'tabla_1.xml')
raiz=archivo_1.getroot()

In [ ]:
raiz

In [ ]:
for nodo in raiz:
    print(nodo.attrib,nodo.text,nodo.tag)
    for sn in nodo:
        print(sn.attrib,sn.text,sn.tag)

{'name': 'Liechtenstein'}
         country
{} 1 rank
{} 2008 year
{} 141100 gdppc
{'name': 'Singapore'}
         country
{} 4 rank
{} 2011 year
{} 59900 gdppc
{'name': 'Panama'}
         country
{} 68 rank
{} 2011 year
{} 13600 gdppc

In [ ]:
archivo_2=ET.parse(ruta+'tabla_2.xml')
root=archivo_2.getroot()
for nodo in root:
    print(nodo.tag,nodo.attrib,nodo.text)

documents {'count': 'N'}

In [ ]:
for nodo in root:
    for subn in nodo:
        print(subn.tag,subn.attrib,subn.text)

document {'KEY': 'e95a9a6c790ecb95e46cf15bee517651', 'web': 'www.ubm/doc004.com'} Nevertheless, high and based on experience, fluctuating throughput levels contradict high reliability.


document {'KEY': 'bc360cfbafc39970587547215162f0db', 'web': 'www.ubm/doc006.com'} As long as the production is not conducted on the basis of concrete customer orders, the companies objectives


document {'KEY': '19e71144c50a8b9160b3f0955e906fce', 'web': 'www.ubm/doc005.com'} Many companies today, in different fields of operations and sizes, have access to a vast amount of data which was not available only a couple of years ago.


document {'KEY': '21d4af9021a174f61b884606c74d9e42', 'web': 'www.ubm/doc002.com'} A famous example of a successful prediction is by the German astronomer Johann Gottfried Galle


document {'KEY': '28a45eb2460899763d709ca00ddbb665', 'web': 'www.ubm/doc001.com'} A more recent example of the same kind is the prediction of the Higgs boson by Francois Englert and Peter Higgs

In [ ]:
#Extraer los datos de tabla_1.xml
d={}
for nodo in raiz:
    d[nodo.tag]=[]
for nodo in raiz:
    d[nodo.tag].append(nodo.attrib['name'])
for nodo in raiz:
    for sn in nodo:
        d[sn.tag]=[]
for nodo in raiz:
    for sn in nodo:
        d[sn.tag].append(sn.text)
d

{'country': ['Liechtenstein', 'Singapore', 'Panama'],
 'rank': ['1', '4', '68'],
 'year': ['2008', '2011', '2011'],
 'gdppc': ['141100', '59900', '13600']}

In [ ]:
pd.DataFrame(d)

         country rank  year   gdppc
0  Liechtenstein    1  2008  141100
1      Singapore    4  2011   59900
2         Panama   68  2011   13600

```python
df_1 = pd.DataFrame(columns = columnas)
for nodo in raiz:
  L = []
  L.append(nodo.attrib['name'])
  for sn in nodo:
    L.append(sn.text)
  df_1 = df_1.append(pd.DataFrame([L], columns=columnas), ignore_index=True)
```

In [ ]:
archivo=ET.parse(ruta+'tabla_2.xml')
raiz=archivo.getroot()

In [ ]:
L=[]
for n in raiz.findall('documents/document'):
    d={}
    d[n.tag]=n.text
    for k,v in n.attrib.items():
        d[k]=v
    L.append(d)
pd.DataFrame(L)

---

In [ ]:
archivo='IFC-Subscriptions-and-Voting-Power-of-Member-Count.xml'
file=ET.parse(ruta+archivo)
root=file.getroot()

for nodo in root:
    for snodo in nodo:
        print(snodo.tag,snodo.attrib,snodo.text)
        for ssnodo in snodo:
            print(ssnodo.tag,ssnodo.attrib,ssnodo.text)

---

# Archivos SHP

Los archivos Shapefile (`.shp`) son un formato estándar para almacenar información geoespacial vectorial. La librería `geopandas` permite leer y manipular estos archivos de manera sencilla. Un Shapefile suele estar acompañado de otros archivos como `.shx` y `.dbf`.

In [ ]:
!pip install geopandas

In [ ]:
#!pip install geopandas

In [ ]:
# %conda !pip !conda
%pip install geopandas

In [ ]:
import geopandas as gpd

In [ ]:
g_df = gpd.read_file('COVID_INDIA_POC-shp/COVID_INDIA_POC.shp')
g_df

In [ ]:
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(12, 8))
g_df.plot(
    ax=ax,
    column=g_df.columns[0],  # Cambia por la columna que quieras destacar
    cmap='viridis',
    edgecolor='black',
    legend=True
)
ax.set_title('COVID_INDIA_POC', fontsize=12)
ax.axis('off')
plt.show()

# Archivos HTML

In [ ]:
# Leer un archivo HTML local
with open(ruta+'ejemplo.html', 'r', encoding='utf-8') as file:
    html_content = file.read()
print(html_content[:500])  # Muestra los primeros 500 caracteres

In [ ]:
#!pip install beautifulsoup4 #Instalar BeautifulSoup si es necesario

In [ ]:
# Analizar HTML con BeautifulSoup
from bs4 import BeautifulSoup
soup = BeautifulSoup(html_content, 'html.parser')

# Extraer el título de la página
titulo = soup.title.string
print('Título de la página:', titulo)

In [ ]:
# Extraer los enlaces de la página
enlaces = soup.find_all('a')
for enlace in enlaces:
    print(enlace.get('href'))

In [ ]:
#!pip install requests # Instalar requests si es necesario
import requests

url = 'https://www.python.org/'
response = requests.get(url)
web_html = response.text

# Analizar el HTML descargado
soup_web = BeautifulSoup(web_html, 'html.parser')

In [ ]:
print(soup_web.title)

###### Ejemplo sencillo webscraping

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
 
url = "https://codedamn-classrooms.github.io/webscraper-python-codedamn-classroom-website/"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")
type(soup)

In [ ]:
#Obtener un dataframe con la información de los productos
products = []

for price_tag in soup.find_all("h4", string=lambda s: s and s.strip().startswith("$")):
    # El nombre del producto es la cadena que sigue después del tag <a> después del precio
    product_link = price_tag.find_next("a")
    if not product_link:
        continue
    product_name = product_link.text.strip()
    product_url = product_link["href"]
    # La descripción es el siguien tag <p> después de la liga del producto
    description_tag = product_link.find_next("p")
    description = description_tag.text.strip() if description_tag else ""
    # Los numero de reviews van después de <div> 
    reviews_tag = product_link.find_next(string=lambda s: s and "review" in s)
    try:
        reviews = int(reviews_tag.strip().split()[0])
    except Exception:
        reviews = None
    # Precio
    try:
        price = float(price_tag.text.strip().replace("$", ""))
    except Exception:
        price = None
 
    products.append({
        "Product Name": product_name,
        "Price": price,
        "Description": description,
        "Reviews": reviews,
        "Product URL": product_url
    })
 
df = pd.DataFrame(products)
df

# Archivos imágen

Las imágenes RGB almacenan información de color en tres canales: Rojo (R), Verde (G) y Azul (B). Para leer y manipular imágenes en Python, se pueden usar las librerías `Pillow` (PIL), `matplotlib` y `numpy`. Esto permite acceder a los valores de los píxeles y realizar análisis o transformaciones.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
I=plt.imread(ruta+'imagen.bmp')
I.shape

In [ ]:
type(I)

In [ ]:
plt.imshow(I)

In [ ]:
I[0,0,0] # pixel (0,0) de la matriz roja

In [ ]:
plt.imshow(I[:,:,0],cmap='gray') # Matriz roja

In [ ]:
G=I.mean(axis=2)
G.shape

In [ ]:
plt.imshow(G)

In [ ]:
G[0,0]

### Ejemplos de aplicaciones en IA para cada tipo de archivo

## 🔎 Ejemplos de aplicaciones en IA para cada tipo de archivo

### 📄 Archivos de texto:

- **Análisis de sentimientos:** Procesar opiniones de usuarios para determinar si son positivas o negativas.
- **Extracción de palabras clave:** Identificar términos importantes en grandes volúmenes de texto.
- **Procesamiento de lenguaje natural (NLP):** Tokenización, lematización y análisis de frecuencia de palabras.
- **Análisis de logs:** Detectar patrones o anomalías en archivos de registro.
- **Generación automática de resúmenes:** Resumir textos extensos con modelos de IA.
- **Reconocimiento de entidades:** Extraer nombres de personas, lugares y organizaciones.
- **Clasificación de documentos:** Categorizar textos en temas o géneros.
- **Traducción automática:** Convertir textos entre idiomas usando IA.

### 📊 Archivos Excel y CSV:

- **Análisis exploratorio de datos (EDA):** Calcular totales, medias y tendencias.
- **Preparación de datos para ML:** Ingeniería de características y limpieza de datos.
- **Reportes automatizados:** Generar resúmenes y exportar resultados.
- **Detección de anomalías:** Identificar valores atípicos.
- **Predicción de tendencias:** Series temporales para prever ventas.
- **Segmentación de clientes:** Agrupar clientes por patrones de compra.
- **Visualización de datos:** Dashboards interactivos y gráficos.

### 🖼️ Archivos de imágenes RGB:

- **Visión por computadora:** Clasificación de imágenes y reconocimiento facial.
- **Procesamiento de imágenes médicas:** Detección de regiones anómalas.
- **Extracción de características visuales:** Histogramas y patrones de color.
- **Detección de objetos:** Localización y clasificación en imágenes.
- **Reconstrucción 3D:** Modelos tridimensionales a partir de imágenes.
- **Segmentación semántica:** Delimitación de regiones específicas.
- **Realidad aumentada:** Superposición de información digital.

### 🗂️ Archivos XML:

- **Integración de datos empresariales:** Extraer información de sistemas ERP.
- **Procesamiento de datos IoT:** Leer registros de sensores.
- **Análisis de publicaciones científicas:** Obtener títulos y autores.
- **Intercambio de datos entre aplicaciones:** Estandarización e interoperabilidad.
- **Validación de esquemas:** Verificar estructura y consistencia.
- **Extracción de datos jerárquicos:** Navegación en árboles complejos.
- **Automatización de reportes:** Generar informes estructurados.

### { } Archivos JSON:

- **Consumo de APIs web:** Obtener y analizar datos en tiempo real.
- **Almacenamiento y análisis de logs:** Procesar registros de aplicaciones.
- **Análisis de datos móviles:** Leer resultados de encuestas y métricas.
- **Integración de datos en tiempo real:** Sensores y dispositivos conectados.
- **Visualización de datos:** Gráficos y mapas interactivos.
- **Entrenamiento de modelos de IA:** Datasets estructurados para algoritmos.
- **Validación y limpieza de datos:** Corrección de inconsistencias.

### 🗺️ Archivos Shapefile (SHP):

- **Análisis geoespacial:** Distancias y relaciones espaciales.
- **Estudios ambientales y urbanos:** Distribución de áreas verdes y zonas urbanas.
- **Modelado de redes y transporte:** Rutas óptimas y predicción de tráfico.
- **Análisis de riesgos naturales:** Identificación de zonas vulnerables.
- **Visualización de mapas temáticos:** Datos demográficos y económicos.
- **Optimización logística:** Rutas de entrega y distribución.

### 🌐 Archivos HTML:

- **Web scraping:** Extracción de datos estructurados de páginas web.
- **Construcción de datasets:** Recolección de información de múltiples páginas.
- **Análisis de enlaces:** Estructura de redes y relaciones.
- **Extracción de tablas:** Datos tabulares para análisis estadístico.
- **Monitoreo de precios:** Rastrear precios en tiendas en línea.
- **Análisis de tendencias:** Identificar temas populares en blogs y noticias.
- **Automatización de reportes web:** Generar informes automáticos.
- **Reconocimiento de patrones visuales:** Detección de banners y anuncios.