<div style="background-color:#000047; padding: 30px; border-radius: 10px; color: white; text-align: center;">
    <img src='Figures/alinco.png' style="height: 100px; margin-bottom: 10px;"/>
    <h1>Preprocesamiento y Análisis Exploratorio de Datos (EDA)</h1>
</div>

El **análisis exploratorio de datos (EDA, por sus siglas en inglés)** es el proceso inicial de examinar y resumir un conjunto de datos para comprender su estructura, características principales, patrones, valores atípicos y relaciones entre variables. Se utilizan técnicas estadísticas, visualizaciones y descripciones numéricas para obtener una visión general de los datos antes de aplicar modelos más complejos.

**¿Por qué es importante para la IA?**

- Permite detectar errores, inconsistencias y valores atípicos que pueden afectar el desempeño de los modelos de IA.
- Ayuda a comprender la distribución y relaciones entre variables, lo que facilita la selección de características relevantes.
- Es clave para preparar y limpiar los datos, asegurando que los algoritmos de IA trabajen con información de calidad.
- Facilita la identificación de patrones y tendencias que pueden guiar la elección del modelo o la estrategia de análisis.

Reduce el riesgo de interpretar mal los resultados, ya que proporciona contexto y conocimiento previo sobre los datos.
En resumen, el EDA es una herramienta fundamental para garantizar que los modelos de IA se construyan sobre bases sólidas y produzcan resultados confiables

### ¿Que preguntas hacernos cuando tenemos archivos en crudo?

- ¿Cuántos registros hay?
    - ¿Son demasiado pocos?
    - ¿Son muchos y no tenemos Capacidad (CPU+RAM) suficiente para procesarlo?
    
- ¿Están todas las filas completas ó tenemos campos con valores nulos?
    - En caso que haya demasiados nulos: ¿Queda el resto de información inútil?
    
- ¿Que datos son discretos y cuales continuos?
    - Muchas veces sirve obtener el tipo de datos: texto, int, double, float
    
- Si es un problema de tipo supervisado:
    - ¿Cuál es la columna de “salida”? ¿binaria, multiclase?
    - ¿Esta balanceado el conjunto salida?
    
- ¿Cuales parecen ser features importantes? ¿Cuales podemos descartar?

- ¿Siguen alguna distribución?

- ¿Hay correlación entre features (características)?

- En problemas de NLP es frecuente que existan categorías repetidas ó mal tipeadas, ó con mayusculas/minúsculas, singular y plural, por ejemplo “Abogado” y “Abogadas”, “avogado” pertenecerían todos a un mismo conjunto.

- ¿Estamos ante un problema dependiente del tiempo? Es decir un TimeSeries.

- Si fuera un problema de Visión Artificial: ¿Tenemos suficientes muestras de cada clase y variedad, para poder hacer generalizar un modelo de Machine Learning?

- ¿Cuales son los Outliers? (unos pocos datos aislados que difieren drásticamente del resto y “contaminan” ó desvían las distribuciones)
    - Podemos eliminarlos? es importante conservarlos?
    - son errores de carga o son reales?
    
- ¿Tenemos posible sesgo de datos? (por ejemplo perjudicar a clases minoritarias por no incluirlas y que el modelo de ML discrimine)

## Ejemplo

In [4]:
import pandas as pd
import numpy as np

In [5]:
df_movie = pd.read_csv('Data/movie_metadata.csv')
df_movie.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

## Preprocesamiento de Datos

#### Análisis de datos Faltantes

In [6]:
df_movie_clean = df_movie.dropna()
df_movie_clean.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000

In [7]:
#fill con la media

In [8]:
#fill con una nueva categoria

#### Limpieza de los datos

In [9]:
dirty_df = pd.read_csv('Data/dirty_data.csv')
dirty_df.head()

   age  birth_date     marital                          people          ssn
0   24  02/12/1954     soltero                Alfonso A,guilar         6439
1   35  05/07/1958      casado               edu6ardo Castillo  689 24 9939
2   46  01-26-1956     Soltero                   jocelyn medel  306-05-2792
3   57  19xx-10-23  divorciado              VICTOR ramos _ _ _  99922a45832
4   10  02/12/0054     SOLTERO  CARLOS EDUARDO; OCHOA ARAMBULA         6439

#### Algunas funciones útiles para limpieza de datos

In [10]:
import string

In [11]:
# remover signos de puntuación
def remove_punctuation(x):
    try:
        x = ''.join(ch for ch in x if ch not in string.punctuation)
    except:
        print(f'{x} no es una cadena de caracteres')
        pass
    return x

In [12]:
#probando la función

In [13]:
def remove_digits(x):
    try:
        x=''.join(ch for ch in x if ch not in string.digits)
    except:
        print(f'{x} no es una cadena de caracteres')
        pass
    return x

In [14]:
#probando la función

In [15]:
# remover espacios en blanco
def remove_whitespace(x):
    try:
        x=' '.join(x.split())
    except:
        pass
    return x

# convertir a minisculas
def lower_text(x):
    try:
        x = x.lower()
    except:
        pass
    return x

#convertir a mayusculas
def upper_text(x):
    try:
        x = x.upper()
    except:
        pass
    return x

# Función que convierta a mayúsculas la primera letra
def capitalize_text(x):
    try:
        x = x.capitalize()
    except:
        pass
    return x
# reemplazar texto
def replace_text(x,to_replace, replacement):
    try:
        x = x.replace(to_replace, replacement)
    except:
        pass
    return x

In [16]:
# Probar en las columnas del dataset

In [17]:
dirty_df

    age  birth_date     marital                            people          ssn
0    24  02/12/1954     soltero                  Alfonso A,guilar         6439
1    35  05/07/1958      casado                 edu6ardo Castillo  689 24 9939
2    46  01-26-1956     Soltero                     jocelyn medel  306-05-2792
3    57  19xx-10-23  divorciado                VICTOR ramos _ _ _  99922a45832
4    10  02/12/0054     SOLTERO    CARLOS EDUARDO; OCHOA ARAMBULA         6439
5    25  05/07/1958      CASado        JOSE MANUEL OCHOA CARDENAS  689 24 9939
6    63  01-26-1956     Soltero         JUAN MARIO; OCHOA NAVARRO  306-05-2792
7    59  19xx?10-23  DIVORCIADO             LUIS ONTANEDA MIJARES  99922a45832
8    69  02/12/1954     soltero       EDUARDO OMAR ORTEGA RAMIREZ          NaN
9    59  05/07/1958         NaN  JOSE ALEJANDRO& PRECIADO GANDARA         6439
10   20  01-26-1956     Soltero  Jose Aantonio Quintero Rodriguez  689 24 9938
11   25  19xx-10-23  divorciado           JOSE ALFONSO RAMIREZ D.  306-06-2792
12   30  02/12/0054     missing           ANA PAULA RANGEL OCHOA&  99922a45845
13   35  05/07/1958      casado                Arturo RUIZ CHAVEZ      missing

### Practica 2: Agregar las funciones en la librería de clase HyAIA

En la Practica 1 se creo un archivo .py donde se pueda almacenar la clas HyAIA, ahora agrega nuevos métodos para la limpieza

## Reporte de Calidad de Datos

Un **reporte de calidad de datos** es un documento o análisis que evalúa el estado y las características de un conjunto de datos antes de su uso en proyectos analíticos o de inteligencia artificial. Este reporte identifica problemas, inconsistencias y riesgos asociados a los datos, ayudando a tomar decisiones sobre limpieza, transformación y uso adecuado.

**Aspectos que suele incluir:**

- Valores faltantes: Cantidad y porcentaje de datos ausentes por columna
- Valores presentes: Cantidad y porcentaje de datos presentes por columna
- Duplicados (Registros repetidos en el dataset).
- Tipos de datos: Verificación de formatos (numérico, texto, fecha, etc.).
- Distribución de variables: Estadísticas descriptivas (media, mediana, moda, etc.).
- Valores atípicos: Detección de datos fuera de rango o inusuales.
- Errores de formato: Problemas en fechas, números, codificación, etc.

Un reporte de calidad de datos permite detectar y corregir problemas antes de entrenar modelos de IA, asegurando resultados más confiables y evitando sesgos o errores en el análisis.

En este apartado crearemos nuestros reportes de calidad de datos

In [18]:
#Dataset de paises
df_countries = pd.read_csv('Data/countries.csv', sep=';')

In [19]:
df_countries.head()

,alpha_2,alpha_3,area,capital,continent,currency_code,currency_name,eqivalent_fips_code,fips,geoname_id,languages,name,neighbours,numeric,phone,population,postal_code_format,postal_code_regex,tld
0,AD,AND,468.0,Andorra la Vella,EU,EUR,Euro,NaN,AN,3041565,ca,Andorra,"ES,FR",20,376,84000,AD###,^(?:AD)*(\d{3})$,.ad
1,AE,ARE,82880.0,Abu Dhabi,AS,AED,Dirham,NaN,AE,290557,"ar-AE,fa,en,hi,ur",United Arab Emirates,"SA,OM",784,971,4975593,NaN,NaN,.ae
2,AF,AFG,647500.0,Kabul,AS,AFN,Afghani,NaN,AF,1149361,"fa-AF,ps,uz-AF,tk",Afghanistan,"TM,CN,IR,TJ,PK,UZ",4,93,29121286,NaN,NaN,.af
3,AG,ATG,443.0,St. John's,NaN,XCD,Dollar,NaN,AC,3576396,en-AG,Antigua and Barbuda,NaN,28,+1-268,86754,NaN,NaN,.ag
4,AI,AIA,102.0,The Valley,NaN,XCD,Dollar,NaN,AV,3573511,en-AI,Anguilla,NaN,660,+1-264,13254,NaN,NaN,.ai

In [26]:
def dqr(data):
    
    #% Lista de variables de la base de datos
    columns = pd.DataFrame(list(data.columns.values), columns=['Columns_Names'], 
                           index=list(data.columns.values))
    
    #Lista de tipos de datos del dataframe
    data_dtypes = pd.DataFrame(data.dtypes, columns=['Dtypes'])
    
    #Lista de valores presentes
    present_values = pd.DataFrame(data.count(), columns=['Present_values'])
    
    #Lista de valores missing (Valores faltantes/nulos nan)
    missing_values = pd.DataFrame(data.isnull().sum(), columns=['Missing_values'])
    
    #Valores unicos de las columnas
    unique_values = pd.DataFrame(columns=['Unique_values'])
    for col in list(data.columns.values):
        unique_values.loc[col] = [data[col].nunique()]
    
    # Información estadística
    #Lista de valores máximos
    max_values = pd.DataFrame(columns=['Max_values'])
    for col in list(data.columns.values):
        try:
            max_values.loc[col] = [data[col].max()]
        except:
            max_values.loc[col]= ['N/A']
            pass

    #Lista de valores mínimos
    min_values = pd.DataFrame(columns=['Min_values'])
    for col in list(data.columns.values):
        try:
            min_values.loc[col] = [data[col].min()]
        except:
            min_values.loc[col]= ['N/A']
            pass

    #Lista de valores con su desviación estandar
    
    #Lista de valores con los percentiles
    
    #Lista de valores con la media
       
    return columns.join(data_dtypes).join(present_values).join(missing_values).join(unique_values).join(max_values).join(min_values)

In [27]:
dqr(df_countries)

,Columns_Names,Dtypes,Present_values,Missing_values,Unique_values,Max_values,Min_values
alpha_2,alpha_2,object,251,1,251,N/A,N/A
alpha_3,alpha_3,object,252,0,252,ZWE,ABW
area,area,float64,252,0,248,17100000.0,0.0
capital,capital,object,246,6,244,N/A,N/A
continent,continent,object,210,42,6,N/A,N/A
currency_code,currency_code,object,251,1,155,N/A,N/A
currency_name,currency_name,object,251,1,82,N/A,N/A
eqivalent_fips_code,eqivalent_fips_code,object,1,251,1,N/A,N/A
fips,fips,object,249,3,249,N/A,N/A
geoname_id,geoname_id,int64,252,0,252,8505033,49518
languages,languages,object,249,3,246,N/A,N/A
name,name,object,252,0,252,Zimbabwe,Afghanistan
neighbours,neighbours,object,165,87,159,N/A,N/A
numeric,numeric,int64,252,0,252,894,0
phone,phone,object,247,5,233,N/A,N/A
population,population,int64,252,0,249,1330044000,0
postal_code_format,postal_code_format,object,154,98,45,N/A,N/A
postal_code_regex,postal_code_regex,object,152,100,54,N/A,N/A
tld,tld,object,250,2,248,N/A,N/A

In [21]:
class HyAIA:
    def __init__(self, df):
        self.data = df
        self.columns = df.columns
        self.dqr = self.get_dqr()

    def dqr(self):
        """
        Método para un reporte de calidad de datos
        """
        return None

## Tarea 1: Modificación de la librería de clase

Tomando en cuenta la libreria creada en clase HyAIA, y la función de reporte de calidad de datos `dqr()`, realizar lo siguiente:

Modificar la función dqr() para tener lo siguiente:

>1.- Modificar la función dqr() para que en el reporte se agregue una columna que sea booleana boolena para representar si una columna es categórica ('Is_categorical') ('Is_categorical' True-->col categorica, False ---> numérica)

>2.- Modificar la función dqr() para que en el reporte se agregue una columna con las categorías de las columnas (valores unicos) que resulten ser categóricas (si las categorias > 10, no agregar esas categorias)

>3.- Aplicar el análisis estadístico de las columnas creadas (max, min, mean, std) solo para las columnas que sean numéricas ('Is_categorical' == False)

### EDA utilizando el reporte de calidad de datos

In [28]:
hy_countries = HyAIA(df_countries)

AttributeError: 'HyAIA' object has no attribute 'get_dqr'

In [ ]:
#Dataframe a analisar
hy_countries.data.head()

In [ ]:
# reporte de calidad de datos
dqr(hy_countries)

In [ ]:
from HAIA import HyAIA as hy

In [ ]:
hy_countries = hy(df_countries)

In [ ]:
#columnas categoricas
hy_countries.categoricos_columns

In [ ]:
# Limpieza de datos:rellenar columnas categoricas con etiqueta ('unk') representando una nueva categoría 
for col_cat in hy_countries.categoricos_columns:
    hy_countries.data[col_cat].fillna('unk', inplace=True)

In [ ]:
# Obtener nuevamente el reporte de calidad de datos
hy_countries.dqr = hy_countries.get_dqr()
hy_countries.dqr

In [ ]:
#eliminar la columna con mayor numero de valores faltantes
hy_countries.data.drop('eqivalent_fips_code', axis=1, inplace=True)

In [ ]:
hy_countries.data.head()

### Iniciando el análisis

In [ ]:
# alpha_3 representa el tag del país
hy_countries.data[hy_countries.data['alpha_3']=='MEX']

In [ ]:
#Cuáles son las lenguas de los países?
hy_countries.data['languages'].unique()

In [ ]:
#Buscar cuales son los países con lengua español en el dataset
df_countries_es = hy_countries.data[hy_countries.data['languages'].str.contains('es')]
df_countries_es.head()

In [ ]:
df_countries_es.shape

In [ ]:
df_countries_es_10 = df_countries_es.sort_values(by='population', ascending=False).head(10)

In [ ]:
# Obtener el top 10 de países con mayor población que hablan Español
df_countries_es_10.set_index('alpha_3')[['population']].plot(kind='bar')

In [ ]:
#Obtener el top 10 de paises con mayor superficie con habla en español
df_countries_es_10.set_index('alpha_3')[['area']].plot(kind='bar')

In [ ]:
#Cuáles son los países con area mayor a 200000?
df_countries_20 = hy_countries.data[hy_countries.data['area']>200000]
df_countries_20.head()

In [ ]:
#Gráfico de los 20 países con mayor superficie
df_countries_20.set_index('alpha_3')['area'].plot(kind='bar', figsize=(20,10))

In [ ]:
df_countries_es[df_countries_es['alpha_3']=='VEN']

In [ ]:
# Paises que tienen frontera con Mexico?
df_countries_es[df_countries_es['neighbours'].str.contains('CO')]

In [ ]:
# Paises que tienen frontera con Colombia, Venezuela, Brazil, Argentina?

## Práctica 3

1. ¿cuáles son los países que tienen como currency name == Peso?
2. ¿cuáles son los 5 países más grandes (área) que tienen como currency name == Peso ?
3. ¿cuáles son los 5 países más grandes (en población) que tienen como currency name == Peso ?
4. ¿Cuáles son los países y currency code, con currency name== Peso?

In [ ]:
df_countries_es.groupby('currency_name')['name'].value_counts()

In [ ]:
#1.-

df_countries_es_peso =df_countries_es[df_countries_es['currency_name']=='Peso']
df_countries_es_peso

In [ ]:
#2.- 
df_countries_es_peso.set_index('alpha_3').
sort_values(by='area', ascending=False)['area'].plot(kind='bar', figsize=(20,10))

In [ ]:
# Cuáles son los países que tienen más de 5 paises con frontera
hy_countries.data.head()

In [ ]:
str_paises = 'ES,FR'.split(',')

In [ ]:
len(str_paises)

In [ ]:
def conteo_frontera(x):
    str_x=[]
    try:
        str_x = x.split(',')
    except:
        pass
    return len(str_x)

In [ ]:
hy_countries_front = hy_countries.data.set_index('name')['neighbours'].apply(conteo_frontera)
hy_countries_front

In [ ]:
hy_countries_front.sort_values(ascending=False).head(30).plot(kind='bar', figsize=(10,8))