<div style="background-color:#e6f2ff; padding:20px; border-radius:10px;">
<img style="float:left; margin-right:20px;" src='Figures/alinco.png' width="120"/>
<h1 style="color:#000047;">Tarea 1: Modificación de la librería de clase</h1>
<br style="clear:both"/>
</div>

<div style="border-left:4px solid #000047; padding:10px; margin-top:10px; background:#f5f5f5;">
<b>Objetivo:</b> Construir la librería de la clase con el objetivo de organizar código funciones y clases útilies durante el proceso del curso.
</div>

Tomando en cuenta la libreria creada en clase `HyAIA`, y la función de reporte de calidad de datos `dqr()`, realizar lo siguiente:

Modificar la función `dqr()` para tener lo siguiente:

**1.- Modificar la función dqr() para que en el reporte se agregue una columna que sea booleana boolena para representar si una columna es categórica ('Is_categorical') ('Is_categorical' True-->col categorica, False ---> numérica)**

In [31]:
print("El bloque de codigo en la fuicion dqr se implemento en la clase original")
                                                        
#def dqr(self):
    
    #is_categorical = pd.DataFrame(columns=['Is_categorical'])
    #for col in list(self.data.columns.values):
     #   if col in self.categoricos_columns:
      #      is_categorical.loc[col] = [True]
       # else:
        #    is_categorical.loc[col] = [False]        
  
    #return columns_names.join(data_dtypes).join(present_values).join(missing_values).join(unique_values).join(max_values).join(min_values).join(is_categorical)

El bloque de codigo en la fuicion dqr se implemento en la clase original

In [32]:
from HyAIA import HyAIA as hia
import pandas as pd
import numpy as np

df_countries = pd.read_csv('Data/countries.csv', sep=';')

hy_countries = hia(df_countries)
hy_countries.dqr()

,Columns_Names,Dtypes,Present_values,Missing_values,Unique_values,Max_values,Min_values,Is_categorical
alpha_2,alpha_2,object,251,1,251,N/A,N/A,True
alpha_3,alpha_3,object,252,0,252,ZWE,ABW,True
area,area,float64,252,0,248,17100000.0,0.0,False
capital,capital,object,246,6,244,N/A,N/A,True
continent,continent,object,210,42,6,N/A,N/A,True
currency_code,currency_code,object,251,1,155,N/A,N/A,True
currency_name,currency_name,object,251,1,82,N/A,N/A,True
eqivalent_fips_code,eqivalent_fips_code,object,1,251,1,N/A,N/A,False
fips,fips,object,249,3,249,N/A,N/A,True
geoname_id,geoname_id,int64,252,0,252,8505033,49518,False
languages,languages,object,249,3,246,N/A,N/A,True
name,name,object,252,0,252,Zimbabwe,Afghanistan,True
neighbours,neighbours,object,165,87,159,N/A,N/A,True
numeric,numeric,int64,252,0,252,894,0,False
phone,phone,object,247,5,233,N/A,N/A,True
population,population,int64,252,0,249,1330044000,0,False
postal_code_format,postal_code_format,object,154,98,45,N/A,N/A,True
postal_code_regex,postal_code_regex,object,152,100,54,N/A,N/A,True
tld,tld,object,250,2,248,N/A,N/A,True

**2.- Modificar la función dqr() para que en el reporte se agregue una columna con las categorías de las columnas (valores unicos) que resulten ser categóricas (si las categorias > 10, no agregar esas categorias)**

In [28]:
from HyAIA import HyAIA as hia2
import pandas as pd
import numpy as np

df_countries = pd.read_csv('Data/countries.csv', sep=';')

hy_countries = hia2(df_countries)
hy_countries.dqr()

,Columns_Names,Dtypes,Present_values,Missing_values,Unique_values,Max_values,Min_values,Is_categorical
alpha_2,alpha_2,object,251,1,251,N/A,N/A,True
alpha_3,alpha_3,object,252,0,252,ZWE,ABW,True
area,area,float64,252,0,248,17100000.0,0.0,False
capital,capital,object,246,6,244,N/A,N/A,True
continent,continent,object,210,42,6,N/A,N/A,True
currency_code,currency_code,object,251,1,155,N/A,N/A,True
currency_name,currency_name,object,251,1,82,N/A,N/A,True
eqivalent_fips_code,eqivalent_fips_code,object,1,251,1,N/A,N/A,False
fips,fips,object,249,3,249,N/A,N/A,True
geoname_id,geoname_id,int64,252,0,252,8505033,49518,False
languages,languages,object,249,3,246,N/A,N/A,True
name,name,object,252,0,252,Zimbabwe,Afghanistan,True
neighbours,neighbours,object,165,87,159,N/A,N/A,True
numeric,numeric,int64,252,0,252,894,0,False
phone,phone,object,247,5,233,N/A,N/A,True
population,population,int64,252,0,249,1330044000,0,False
postal_code_format,postal_code_format,object,154,98,45,N/A,N/A,True
postal_code_regex,postal_code_regex,object,152,100,54,N/A,N/A,True
tld,tld,object,250,2,248,N/A,N/A,True

**3.- Aplicar el análisis estadístico de las columnas creadas (max, min, mean, std) solo para las columnas que sean numéricas ('Is_categorical' == False)**